PayerEntity|VendorCode|InvoiceNumber|DocType|DocAmt|DiscAmt|AmountToPay|InvoiceDate|DueDate|VendorName|Address1|Address2|City|State|Zip|Country|LocationCode|CheckNum|Memo|Routing|Accountnumber|VendorEmailAddress|PaymentMethod
<#list documentsList as document><#-- Start Document Loop -->
	<#list document.documentLines as docline><#-- Start DocumentList Loop -->
		<#if !document.paymentsConsolidate><#--    ********************************  Is not a consolidated batch  ******************************    -->
<#if paymentModeInfo.clientIdToken?exists && paymentModeInfo.clientIdToken?length gt 0>${paymentModeInfo.clientIdToken}</#if>|<#if docline.paymentsVendorId?exists>${docline.paymentsVendorId}</#if>|<#if docline.paymentsNumber?exists>${docline.paymentsNumber}</#if>|INV|<#if docline.lineTotal?exists>${docline.lineTotal?string("0.00")}</#if>|<#if docline.paymentsDiscountAmount?exists>${docline.paymentsDiscountAmount?string("0.00")}</#if>|<#if docline.lineTotal?exists && docline.paymentsDiscountAmount?exists>${(docline.lineTotal - docline.paymentsDiscountAmount)?string("0.00")}<#elseif docline.lineTotal?exists && !docline.paymentsDiscountAmount?exists>${docline.lineTotal}</#if>|<#if docline.paymentsDate?exists>${docline.paymentsDate?string("yyyy-MM-dd")}</#if>|<#if docline.paymentsDueDate?exists>${docline.paymentsDueDate?string("yyyy-MM-dd")}</#if>|<#if docline.paymentsVendorName?exists>${docline.paymentsVendorName}</#if>|<#if docline.paymentsAddr1?exists>${docline.paymentsAddr1}</#if>|<#if docline.paymentsAddr2?exists>${docline.paymentsAddr2}</#if>|<#if docline.paymentsCity?exists>${docline.paymentsCity}</#if>|<#if docline.paymentsState?exists && docline.paymentsState?length gt 0>${docline.paymentsState}</#if>|<#if docline.paymentsPostalCode?exists>${docline.paymentsPostalCode}</#if>|<#if docline.paymentsCountry?exists>${docline.paymentsCountry}</#if>|<#if docline.paymentsAddrType?exists>${docline.paymentsAddrType}<#else>payeeAddress</#if>|<#if docline.paymentsPayRef?exists && document.tbdString9?upper_case?matches("CHECK")>${docline.paymentsPayRef}<#elseif docline.seqId?exists>${docline.seqId?c}</#if>|<#if docline.paymentsCheckStubMessage?exists && docline.paymentsCheckStubMessage != "">${docline.paymentsCheckStubMessage}</#if>|<#if docline.paymentsVendorBankRoutingNo?exists>${docline.paymentsVendorBankRoutingNo}</#if>|<#if docline.paymentsVendorBankAcctNo?exists>${docline.paymentsVendorBankAcctNo}</#if>|<#if docline.paymentsEmail?exists>${docline.paymentsEmail}</#if>|<#if document.tbdString9?exists>${document.tbdString9}</#if>
		<#elseif document.paymentsConsolidate><#--    ********************************  Is a consolidated batch  ******************************    -->
			<#if !docline.paymentsSeparateCheck><#--    ********************************  Is not a Separate check  ******************************    -->
				<#if !docline.subLineTypeNumber?contains(".")><#--    ********************************  Is a payment line  ******************************    -->
					<#assign paymentRef = "">
					<#if docline.paymentsPayRef?exists && document.tbdString9?upper_case?matches("CHECK")><#assign paymentRef = docline.paymentsPayRef><#elseif docline.seqId?exists><#assign paymentRef = docline.seqId?c></#if>
					<#list document.documentLines as docline2><#--  **********************************  Loop through the Invoice details  **********************************  -->  
						<#if docline2.subLineTypeNumber?contains(".") && docline2.subLineTypeNumber?keep_before(".") == docline.subLineTypeNumber><#--  **********************************  Print invoice details if they match payments  **********************************  -->
<#if paymentModeInfo.clientIdToken?exists && paymentModeInfo.clientIdToken?length gt 0>${paymentModeInfo.clientIdToken}</#if>|<#if docline2.paymentsVendorId?exists>${docline2.paymentsVendorId}</#if>|<#if docline2.paymentsNumber?exists>${docline2.paymentsNumber}</#if>|INV|<#if docline2.lineTotal?exists>${docline2.lineTotal?string("0.00")}</#if>|<#if docline2.paymentsDiscountAmount?exists>${docline2.paymentsDiscountAmount?string("0.00")}</#if>|<#if docline2.lineTotal?exists && docline2.paymentsDiscountAmount?exists>${(docline2.lineTotal - docline2.paymentsDiscountAmount)?string("0.00")}<#elseif docline2.lineTotal?exists && !docline2.paymentsDiscountAmount?exists>${docline2.lineTotal}</#if>|<#if docline2.paymentsDate?exists>${docline2.paymentsDate?string("yyyy-MM-dd")}</#if>|<#if docline2.paymentsDueDate?exists>${docline2.paymentsDueDate?string("yyyy-MM-dd")}</#if>|<#if docline2.paymentsVendorName?exists>${docline2.paymentsVendorName}</#if>|<#if docline2.paymentsAddr1?exists>${docline2.paymentsAddr1}</#if>|<#if docline2.paymentsAddr2?exists>${docline2.paymentsAddr2}</#if>|<#if docline2.paymentsCity?exists>${docline2.paymentsCity}</#if>|<#if docline2.paymentsState?exists && docline2.paymentsState?length gt 0>${docline2.paymentsState}</#if>|<#if docline2.paymentsPostalCode?exists>${docline2.paymentsPostalCode}</#if>|<#if docline2.paymentsCountry?exists>${docline2.paymentsCountry}</#if>|<#if docline2.paymentsAddrType?exists>${docline2.paymentsAddrType}<#else>payeeAddress</#if>|${paymentRef}|<#if docline2.paymentsCheckStubMessage?exists && docline2.paymentsCheckStubMessage != "">${docline2.paymentsCheckStubMessage}</#if>|<#if docline.paymentsVendorBankRoutingNo?exists>${docline.paymentsVendorBankRoutingNo}</#if>|<#if docline.paymentsVendorBankAcctNo?exists>${docline.paymentsVendorBankAcctNo}</#if>|<#if docline2.paymentsEmail?exists>${docline2.paymentsEmail}</#if>|<#if document.tbdString9?exists>${document.tbdString9}</#if>
						</#if>
					</#list><#-- End of Invoice Loop  -->
				</#if><#--    ********************************  End Payment Line Check IF  ******************************    -->
			<#elseif docline.paymentsSeparateCheck><#--    ********************************  Is a Separate check  ******************************    -->
<#if paymentModeInfo.clientIdToken?exists && paymentModeInfo.clientIdToken?length gt 0>${paymentModeInfo.clientIdToken}</#if>|<#if docline.paymentsVendorId?exists>${docline.paymentsVendorId}</#if>|<#if docline.paymentsNumber?exists>${docline.paymentsNumber}</#if>|INV|<#if docline.lineTotal?exists>${docline.lineTotal?string("0.00")}</#if>|<#if docline.paymentsDiscountAmount?exists>${docline.paymentsDiscountAmount?string("0.00")}</#if>|<#if docline.lineTotal?exists && docline.paymentsDiscountAmount?exists>${(docline.lineTotal - docline.paymentsDiscountAmount)?string("0.00")}<#elseif docline.lineTotal?exists && !docline.paymentsDiscountAmount?exists>${docline.lineTotal}</#if>|<#if docline.paymentsDate?exists>${docline.paymentsDate?string("yyyy-MM-dd")}</#if>|<#if docline.paymentsDueDate?exists>${docline.paymentsDueDate?string("yyyy-MM-dd")}</#if>|<#if docline.paymentsVendorName?exists>${docline.paymentsVendorName}</#if>|<#if docline.paymentsAddr1?exists>${docline.paymentsAddr1}</#if>|<#if docline.paymentsAddr2?exists>${docline.paymentsAddr2}</#if>|<#if docline.paymentsCity?exists>${docline.paymentsCity}</#if>|<#if docline.paymentsState?exists && docline.paymentsState?length gt 0>${docline.paymentsState}</#if>|<#if docline.paymentsPostalCode?exists>${docline.paymentsPostalCode}</#if>|<#if docline.paymentsCountry?exists>${docline.paymentsCountry}</#if>|<#if docline.paymentsAddrType?exists>${docline.paymentsAddrType}<#else>payeeAddress</#if>|<#if docline.paymentsPayRef?exists && document.tbdString9?upper_case?matches("CHECK")>${docline.paymentsPayRef}<#elseif docline.seqId?exists>${docline.seqId?c}</#if>|<#if docline.paymentsCheckStubMessage?exists && docline.paymentsCheckStubMessage != "">${docline.paymentsCheckStubMessage}</#if>|<#if docline.paymentsVendorBankRoutingNo?exists>${docline.paymentsVendorBankRoutingNo}</#if>|<#if docline.paymentsVendorBankAcctNo?exists>${docline.paymentsVendorBankAcctNo}</#if>|<#if docline.paymentsEmail?exists>${docline.paymentsEmail}</#if>|<#if document.tbdString9?exists>${document.tbdString9}</#if>
			</#if><#--    ********************************  End Separate Check IF  ******************************    -->
		</#if><#--    ********************************  End Consolidated IF  ******************************    -->
	</#list><#-- End DocumentList Loop -->
</#list><#-- End Document Loop -->